version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"

  wishlist-service:
    build: .
    container_name: wishlist-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/wishlist
    depends_on:
      - mongo

volumes:
  mongo-data:
